// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    NaviBar: typeof import('./src/components/NaviBar.vue')['default']
    SelectionOverlay: typeof import('./src/components/SelectionOverlay.vue')['default']
    TimeDial: typeof import('./src/components/TimeDial.vue')['default']
    TimeSchedular: typeof import('./src/components/TimeSchedular.vue')['default']
    TimeZoneItem: typeof import('./src/components/TimeZoneItem.vue')['default']
    TimeZoneSearch: typeof import('./src/components/TimeZoneSearch.vue')['default']
  }
}

export {}
