// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TimeSchedular: typeof import('./src/components/TimeSchedular.vue')['default']
    TimeZoneSearch: typeof import('./src/components/TimeZoneSearch.vue')['default']
  }
}

export {}
